# GO_STP_5823

**1.Import the numpy package under the name np and Print the numpy version and the configuration**

In [1]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/91834/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/91834/anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/91834/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/91834/anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/91834/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/91834/anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/91834/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/91834/anaconda\\Library\\include']
None


**2.Create a null vector of size 10**

In [2]:
a=np.zeros((2,5))
print(a)
print("size of the null vector is:",a.size)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
size of the null vector is: 10


**3.Create Simple 1-D array and check type and check data types in array**

In [3]:
a=np.array([1,2,3,4,5])
print(a)
print("The type of a is:",type(a))
print("Data types in array is:",a.dtype)

[1 2 3 4 5]
The type of a is: <class 'numpy.ndarray'>
Data types in array is: int32


**4.How to find number of dimensions, bytes per element and bytes of memory used?**

In [5]:
arr=np.array([[1,2,3],[6,7,8]])
print("dimensions of array:",arr.ndim)
print("Bytes per element:",arr.itemsize)
print("Bytes used in array:",arr.nbytes)

dimensions of array: 2
Bytes per element: 4
Bytes used in array: 24


**5.Create a null vector of size 10 but the fifth value which is 1**

In [6]:
a=np.zeros((2,5))
a[0,4]=1
print(a)

[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


**6.Create a vector with values ranging from 10 to 49**

In [7]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**7.Reverse a vector (first element becomes last)**

In [9]:
arr1=np.arange(1,9)
print(arr1)
print("Reverse of the vector:",arr1[::-1])

[1 2 3 4 5 6 7 8]
Reverse of the vector: [8 7 6 5 4 3 2 1]


**8.Create a 3x3 matrix with values ranging from 0 to 8**

In [10]:
a=np.arange(0,9).reshape((3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**9.Find indices of non-zero elements from [1,2,0,0,4,0]**

In [12]:
a=np.array([1,2,0,0,4,0])
print(a)
print("non_zero elements of the array:",a[np.nonzero(a)])

[1 2 0 0 4 0]
non_zero elements of the array: [1 2 4]


**10.Create a 3x3 identity matrix**

In [13]:
i=np.identity(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**11.Create a 3x3x3 array with random values**

In [14]:
a=np.random.rand(3,3,3)
print(a)

[[[7.42142172e-01 4.69967212e-01 5.13326926e-02]
  [7.77637711e-01 9.44383607e-01 4.04012840e-01]
  [8.35250964e-01 1.40689047e-01 8.53823322e-01]]

 [[8.01830152e-01 4.43848365e-01 4.72444517e-04]
  [5.12806865e-01 6.34983327e-01 9.03479966e-01]
  [6.58552007e-01 2.54044174e-01 1.46679736e-01]]

 [[4.13803334e-01 6.44978550e-01 1.61009557e-01]
  [4.42754440e-01 5.84697559e-01 5.60522179e-01]
  [1.33723113e-01 8.16803368e-01 7.00631295e-01]]]


**12.Create a 10x10 array with random values and find the minimum and maximum values**

In [15]:
a=np.random.rand(10,10)
print(a)

[[0.18224151 0.99662796 0.42441753 0.15569974 0.96847197 0.36506645
  0.65357888 0.75995263 0.61932844 0.46474711]
 [0.46482213 0.82624297 0.5047918  0.24935346 0.84048927 0.7761587
  0.94360297 0.1487879  0.60461068 0.5350373 ]
 [0.32412986 0.31738552 0.34841387 0.34242752 0.80473157 0.92900087
  0.36275888 0.74566499 0.67841072 0.56949579]
 [0.20175335 0.66937964 0.49749349 0.73441933 0.24023771 0.78951408
  0.91392604 0.78735135 0.70385941 0.3018343 ]
 [0.63980668 0.74994478 0.7882948  0.8598123  0.08107866 0.17309629
  0.56181798 0.82865392 0.30191982 0.79509785]
 [0.53050182 0.50023879 0.23183473 0.38631579 0.44898166 0.46606197
  0.21654531 0.71471284 0.10232872 0.02724918]
 [0.83586848 0.15423756 0.75374717 0.32859112 0.88456193 0.35590149
  0.35403611 0.59177173 0.72253648 0.28843411]
 [0.22456551 0.54320112 0.00332777 0.26515584 0.18418507 0.50211044
  0.60453645 0.57835144 0.93730476 0.41433324]
 [0.52564665 0.50966775 0.91444713 0.34396226 0.03036749 0.92691978
  0.27654847 

In [17]:
print("minimum value",a.min())
print("minimum value",a.max())

minimum value 0.003327769517428303
minimum value 0.9966279603344235


**13.Create a random vector of size 30 and find the mean value**

In [19]:
arr1=np.random.rand(30)
print(arr1)

[0.00367733 0.40536823 0.76650939 0.75674658 0.42706144 0.37370023
 0.4417622  0.01611679 0.57753143 0.05351725 0.10377457 0.8033153
 0.9609871  0.0683123  0.69919205 0.60725538 0.4532463  0.26696488
 0.32900633 0.88757857 0.51978381 0.27421873 0.7169015  0.43873658
 0.1382961  0.63636786 0.0311733  0.66388562 0.70184329 0.98282435]


In [20]:
print("mean value is",arr1.mean())

mean value is 0.4701884927548834


**14.Create a 2d array with 1 on the border and 0 inside**

In [21]:
arr1=np.ones((6,6))
arr1[1:-1,1:-1]=0
print(arr1)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


**15.How to add a border (filled with 0's) around an existing array?**

In [22]:
arr2=np.random.randint(5,size=(4,4))
arr2=np.pad(arr2,pad_width=1,constant_values=0)
print(arr2)

[[0 0 0 0 0 0]
 [0 2 0 1 3 0]
 [0 2 3 0 3 0]
 [0 3 3 2 0 0]
 [0 2 3 3 3 0]
 [0 0 0 0 0 0]]


**16.How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?**

In [26]:
arr=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
# to get 
print(arr[1,5])
# to get the column
print(arr[0,[1,3,5]])
#replacing 13 by 20
arr[1,5]=20
print(arr)


13
[2 4 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


**17.How to Convert a 1D array to a 2D array with 2 rows**

In [27]:
arr1=np.linspace(1,6,6)
print(arr1)
print("dimension of array:",arr1.ndim)
arr2=arr1.reshape((2,3))
print(arr2)
print("dimension of array after reshaping:",arr2.ndim)


[1. 2. 3. 4. 5. 6.]
dimension of array: 1
[[1. 2. 3.]
 [4. 5. 6.]]
dimension of array after reshaping: 2


**18.Create the following pattern without hardcoding. Use only numpy functions and the below input array a.**

* Input: a = np.array([1,2,3])`
* array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


In [28]:
a=np.array([1,2,3])
a1=a.repeat(3),np.tile(a,3)
np.concatenate(a1)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

**19.Write a program to show how Numpy taking less memory compared to Python List?**

In [29]:
import sys
a=1
list1=range(1000)
arr1=np.arange(1000)
#memory size of list
print("memory used by listst:",sys.getsizeof(a)*len(list1))
#memory size of numpy array
print("memory used by numpy:",arr1.size*arr1.itemsize)

memory used by listst: 28000
memory used by numpy: 4000


**20.Write a program to show how Numpy taking less time compared to Python List?**

In [30]:
import time
size=1000000
l1=range(size)
l2=range(size)
start=time.time()
result=[(x*y) for x,y in zip(l1,l2)]
print("time taken in lists",(time.time()-start)*1000)
size=1000000
n1=np.arange(size)
n2=np.arange(size)
start=time.time()
result1=n1*2
print("time taken in numpy arrays",(time.time()-start*1000))

time taken in lists 189.82553482055664
time taken in numpy arrays -1620857157167.7542
